### ISSUE TITLE
Required, Required

### ISSUE THREAD

**Issue by AutoSponge** [dequelabs/pattern-library#15]
[This reference](https://dequeuniversity.com/tips/identify-required-elements) contains two patterns for required form fields. However, [this example](https://pattern-library.dequelabs.com/components/fields) in the pattern library uses a hybrid:

```html
<div class="dqpl-field-wrap">
      <label class="dqpl-label dqpl-required" for="required-field">First name</label>
      <input class="dqpl-text-input" type="text" id="required-field" aria-required="true">
      <div class="dqpl-error-wrap"></div>
</div>
```

```css
.dqpl-label.dqpl-required:after {
    content: 'Required';
...
}
```

This causes VoiceOver in a modern browser (and possibly other AT/browser combinations) to double announce "required": once for the label text `::after` content and again because of the aria attribute. Additionally, the absence of the `required` attribute may be purposeful, but it's in conflict with the other recommendation.

I think it's best to place `aria-hidden` or `role=presentation` on the "required" label text and add the `required` attribute to the input. If the browser/AT is old and does not support aria/HTML5, then the label text will be read. Otherwise, only the attribute will be announced (and I'm not aware of any AT that double announces for `required` and `aria-required` although not all AT honor both).

If this sounds reasonable, I can make a PR.

**Comment by schne324** [comment]
You bring up a very good point!
We definitely don't want to apply `aria-hidden="true"` to the label element because that would take away the entire accessible text for the input resulting in a read out like "Edit Text required" rather than the target readout of "First Name, required, edit text".  I think the best solution is to apply the label's "required" text to an `aria-hidden` span within the label so the accessible text calculation only includes the label text without "required".  For example:

```html
<label class="dqpl-label" for="password">
    Password
    <span class="dqpl-required-text" aria-hidden="true">Required</span>
</label>
<input class="dqpl-text-input" type="text" id="password" aria-required="true"/>
```
A few things to keep in mind if you'd like to PR a fix:
- Remove the `::after` hooks (https://github.com/dequelabs/pattern-library/blob/master/lib/commons/forms.less#L87) and apply these same styles to the `dqpl-required-text` element
- Apply the error styling to the new `dqpl-required-text` element within the label (https://github.com/dequelabs/pattern-library/blob/master/lib/commons/forms.less#L96)
- Don't worry about documenting these changes in the wiki (I will take care of that)
- I will handle updating the demo site (along with the code snippets) https://pattern-library.dequelabs.com/components/fields

Thanks!
