### ISSUE TITLE
question about disabled buttons

### ISSUE THREAD

**Issue by eriklieben** [dequelabs/pattern-library#29]
Hi,

Just found a link to this library on twitter and started looking around, was just wondering if there any particular reason you need to disable the button using the class 'dqpl-disabled'? Has that anything to do with accessibility?

```html
<button class="dqpl-button-primary dqpl-disabled" type="button">PRIMARY DISABLED</button>
```

Asking it, because in the above state the button itself would still fire events, while it looks disabled to the user. 

If you set the ```disabled``` attribute it would not fire events anymore:

```html
<button class="dqpl-button-primary dqpl-disabled" type="button" disabled>PRIMARY DISABLED</button>
```

And then you could style it using the ```:disabled``` pseudo CSS selector (https://developer.mozilla.org/nl/docs/Web/CSS/:disabled) and ```button[disabled]``` (if you need to support older browsers).

Then the following markup would work:

```html
<button class="dqpl-button-primary" disabled>PRIMARY DISABLED</button>
```

```css
button[disabled],
button:disabled {
....
}
```

Wondering if the above breaks accessibility in some way, because then I got some code to refactor :-)

Thanks,

Erik

**Comment by schne324** [comment]
Hey, good question. At the moment the only css hooks for the disabled visual styling is by using the "dqpl-disabled" class (so no, it doesn't have anything to do with accessibility), but it is expected that it is used in unison with `aria-disabled="true"` as well as the `disabled` attribute.  You do have a valid point about using pseudo-selectors for the styling rather than relying on an additional class though. 

It looks like the example (https://pattern-library.dequelabs.com/components/buttons) is implemented properly while the code snippet (which you have pointed out) is missing the required attributes.

I'm going to go ahead and add the disabled attribute css hook so you can just:
```html
<button class="dqpl-button-primary" disabled aria-disabled="true">PRIMARY DISABLED</button>
```

Thanks!

**Comment by eriklieben** [comment]
Btw. according to the w3c spec the ```aria-disabled="true"``` isn't required in this case. Not sure how each of the a11y browser/tools handles and/or support this, but NVDA seems to be okay with only having disabled.

https://www.w3.org/TR/html-aria/#attr-disabled
```
Use the disabled attribute on any element that is allowed the disabled attribute in HTML5.

Only use the aria-disabled attribute for elements that are not allowed to have a disabled 
attribute in HTML5
```
https://www.w3.org/TR/html/sec-forms.html#enabling-and-disabling-form-controls-the-disabled-attribute
```
A form control is disabled if any of the following conditions are met:

The element is a button, input, select, or textarea element, and the disabled attribute is specified on this element (regardless of its value).
```

**Comment by schne324** [comment]
Yea the more recent versions of the most commonly used screen readers don't require the use of `aria-disabled="true"` but to support older versions and less common AT, I'd still recommend using both.
