### ISSUE TITLE
Use JS to set the value of a select?

### ISSUE THREAD

**Issue by lhenze** [dequelabs/pattern-library#84]
Similar to issue #83 but the inverse...
I'd like to dynamically set the active state of the select.
Is there a way to do this? 
Thanks!

**Comment by schne324** [comment]
Hey @lhenze, great question!

I will leave this ticket open as a feature request because theres not a very clean way of accomplishing this at the moment but it _is_ possible with a little extra code...I've updated the [codepen demo](https://codepen.io/schne324/pen/XyRvMx) in which you can click the buttons to programmatically set the active state of the select (its done so by firing a mousedown event on the desired active option).

Thanks!

**Comment by lhenze** [comment]
Aha, that's a neat approach.  Thanks @schne324!

**Comment by schne324** [comment]
#111 resolves this issue. Below is an example of how to use it (keep in mind we just updated the [select component in a non-backwards-compatible way](https://github.com/dequelabs/pattern-library/wiki/selects))

```js
// grab the select button
const select = document.querySelector('[aria-haspopup=listbox]');
select.addEventListener('dqpl:select:change', ({ detail }) => {
  console.log(`New value is ${detail.value}`)
});
```
